version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
       limits:
         cpus: '4'
         memory: '20GB'

  redis-load-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
    volumes:
      - ./output:/data
    depends_on:
      - redis

  redis-stat:
    image: insready/redis-stat
    container_name: redis-stat
    ports:
      - "63790:63790"
    command: --server redis
    depends_on:
      - redis
    links:
      - redis:redis
